# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=200)),
                ('numb_fam', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.IntegerField(default=0)),
                ('seq_id', models.IntegerField(default=0)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=20)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='wateryield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('water_yield', models.IntegerField(default=0)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.sequence')),
            ],
        ),
        migrations.CreateModel(
            name='wells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=20)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=20)),
                ('depth', models.IntegerField(default=0)),
                ('avg_yield', models.IntegerField(default=0)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.sequence')),
            ],
        ),
        migrations.AlterField(
            model_name='households',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='households',
            name='lon',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AddField(
            model_name='sequence',
            name='house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Households'),
        ),
        migrations.AddField(
            model_name='person',
            name='house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Households'),
        ),
        migrations.AddField(
            model_name='crops',
            name='farm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.sequence'),
        ),
        migrations.AddField(
            model_name='area',
            name='farm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.sequence'),
        ),
    ]
