# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_households_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='crops',
            name='crop_area',
            field=models.IntegerField(default=0),
        ),
    ]
